language: elixir
elixir: 1.4.5
sudo: false
notifications:
  recipients:
  - bruce.williams@cargosense.com
addons:
  apt:
    packages:
    - texlive-latex-base
otp_release:
- 19.3
- 20.0
script: "MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, test"
